modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/Waystones/issues"

[[mods]]
modId="waystones"
version="${file.jarVersion}"
displayName="Waystones"
displayURL="https://mods.twelveiterations.com/mc/waystones"
logoFile="waystones-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Teleport back to activated waystones. For Survival, Adventure or Servers.
'''

[[dependencies.waystones]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waystones]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waystones]]
    modId="balm"
    mandatory=true
    versionRange="[7.0.0,)"
    ordering="NONE"
    side="BOTH"